[package]
name = "systema"
version = "0.1.0"
edition = "2024"

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }

once_cell = "1.20"
itertools = "0.14"
