[package]
name = "systema"
version = "0.1.0"
edition = "2024"
license = "MPL-2"

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }

once_cell = "1.20"
parking_lot = "0.12"

derive_more = { version = "2", features = ["debug"] }